Repository Inkacoders/Inka-homepage, pull requests merged in 2022-04, with the labels that each got.

#22 Files structure created
  package.json
  src/js/functions.js
  src/js/index.js
  src/styles/community.css
  src/styles/components/burger-btn.css
  src/styles/components/card.css
  src/styles/components/community.css
  src/styles/components/form.css
  src/styles/components/grid-gallery.css
  src/styles/components/header.css
  src/styles/components/home.css
  src/styles/components/icon.css
  src/styles/components/menu.css
  src/styles/components/portfolio.css
  src/styles/components/services.css
  src/styles/components/testimonial.css
  src/styles/elements/body.css
  src/styles/header.css
  src/styles/icon.css
  src/styles/main.css
  src/styles/menu.css
  src/styles/objects/wrapper.css
  src/styles/settings/fonts.css
  src/styles/settings/variables.css
Labels: Fix

#23 Menu resets based on the device
  src/js/functions.js
  src/js/index.js
Labels: Fix

#24 Metatag, meta info and meta thumbnail created
  public/index.html
  src/assets/images/Thumbnail.jpeg
Labels: Feature

#25 Footer structure created and spancing fixed
  public/index.html
  src/assets/fonts/icomoon.eot
  src/assets/fonts/icomoon.svg
  src/assets/fonts/icomoon.ttf
  src/assets/fonts/icomoon.woff
  src/assets/images/inka-white-2x.webp
  src/assets/images/inka-white.webp
  src/assets/images/inka.svg
  src/js/index.js
  src/styles/components/footer-menu.css
  src/styles/components/footer.css
  src/styles/components/form.css
  src/styles/components/header.css
  src/styles/components/home.css
  src/styles/components/icon.css
  src/styles/components/logo.css
  src/styles/components/portfolio.css
  src/styles/components/services.css
  src/styles/components/social-media.css
  src/styles/components/testimonial.css
  src/styles/elements/body.css
  src/styles/objects/wrapper.css
  src/styles/settings/fonts.css
  src/styles/settings/variables.css
Labels: Feature, Component, Fix

#26 mixins added
  src/styles/settings/_mixins.scss
Labels: Feature
